e_commerce_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls') )

]

main_app/urls.py
from django.urls import path
from . import views # Import views to connect routes to view functions
from . import views

urlpatterns = [
    # Routes will be added here
    path('', views.Home , name='home'),
    path('accounts/signup/', views.signup, name='signup'),
    path('accounts/signin/', views.signin.as_view(), name='signin'),
    path('product/<str:sku>/',views.show_product, name='show_product') ,
    path('addtocart/', views.add_to_cart, name='addtocart'),
    path('cart/', views.view_cart , name='cart'),
    path('updatecart/<str:cartItemId>/', views.update_cart, name="update_cart"),
    path('search/', views.product_search , name="product_search"),
    path('addtowishlist/', views.add_to_wishlist , name="addtowishlist"),
    path('wishlist/', views.view_wishlist , name="view_wishlist"),
    path('removefromwishlist/', views.remove_wishlist_item, name="remove_from_wishlist"),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from shortuuid.django_fields import ShortUUIDField
# Create your models here.

CATEGORIES = (
    ('blush', 'Blush'),
    ('bronzer', 'Bronzer'),
    ('eyebrow', 'Eyebrow'),
    ('eyeliner', 'Eyeliner'),
    ('eyeshadow', 'Eyeshadow'),
    ('foundation', 'Foundation'),
    ('lip liner', 'Lip Liner'),
    ('lipstick', 'Lipstick'),
    ('mascara', 'Mascara'),
    ('nail polish', 'Nail Polish'),
)


class Category(models.Model):
    categoryId = ShortUUIDField(unique = True, length=10, max_length=20, prefix="cat", alphabet="abcdefghijk123456789")
    title = models.CharField(choices=CATEGORIES)
    image = models.CharField()

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.title

class Product(models.Model):

    BRANDS = (
    ('almay', 'Almay'),
    ('alva', 'Alva'),
    ('anna sui', 'Anna Sui'),
    ('annabelle', 'Annabelle'),
    ('benefit', 'Benefit'),
    ('boosh', 'Boosh'),
    ('burt\'s bees', 'Burt\'s Bees'),
    ('butter london', 'Butter London'),
    ('c\'est moi', 'C\'est Moi'),
    ('cargo cosmetics', 'Cargo Cosmetics'),
    ('china glaze', 'China Glaze'),
    ('clinique', 'Clinique'),
    ('coastal classic creation', 'Coastal Classic Creation'),
    ('colourpop', 'Colourpop'),
    ('covergirl', 'Covergirl'),
    ('dalish', 'Dalish'),
    ('deciem', 'Deciem'),
    ('dior', 'Dior'),
    ('dr. hauschka', 'Dr. Hauschka'),
    ('e.l.f.', 'E.L.F.'),
    ('essie', 'Essie'),
    ('fenty', 'Fenty'),
    ('glossier', 'Glossier'),
    ('green people', 'Green People'),
    ('iman', 'Iman'),
    ('l\'oreal', 'L\'Oreal'),
    ('lotus cosmetics usa', 'Lotus Cosmetics USA'),
    ('maia\'s mineral galaxy', 'Maia\'s Mineral Galaxy'),
    ('marcelle', 'Marcelle'),
    ('marienatie', 'Marienatie'),
    ('maybelline', 'Maybelline'),
    ('milani', 'Milani'),
    ('mineral fusion', 'Mineral Fusion'),
    ('misa', 'Misa'),
    ('mistura', 'Mistura'),
    ('moov', 'Moov'),
    ('nudus', 'Nudus'),
    ('nyx', 'NYX'),
    ('orly', 'Orly'),
    ('pacifica', 'Pacifica'),
    ('penny lane organics', 'Penny Lane Organics'),
    ('physicians formula', 'Physicians Formula'),
    ('piggy paint', 'Piggy Paint'),
    ('pure anada', 'Pure Anada'),
    ('rejuva minerals', 'Rejuva Minerals'),
    ('revlon', 'Revlon'),
    ('sally b\'s skin yummies', 'Sally B\'s Skin Yummies'),
    ('salon perfect', 'Salon Perfect'),
    ('sante', 'Sante'),
    ('sinful colours', 'Sinful Colours'),
    ('smashbox', 'Smashbox'),
    ('stila', 'Stila'),
    ('suncoat', 'Suncoat'),
    ('w3llpeople', 'W3LLPeople'),
    ('wet n wild', 'Wet n Wild'),
    ('zorah', 'Zorah'),
    ('zorah biocosmetiques', 'Zorah Biocosmetiques'),
)

    productId = ShortUUIDField(unique = True, length=10, max_length=20, prefix="pro", alphabet="abcdefghijk123456789")
    title = models.CharField(max_length=150)
    product_type = models.CharField(max_length=150)
    image = models.CharField()
    description = models.TextField(null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    brand = models.CharField(choices=BRANDS)
    featured = models.BooleanField(default=True)
    on_sale = models.BooleanField(default=False)

    def __str__(self):
        return self.title

class ProductColors(models.Model):
    colorId =ShortUUIDField(unique = True, length=10, max_length=20, prefix="col", alphabet="abcdefghijk123456789")
    hex_value = models.CharField(max_length=50)
    color_name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "Product Colors"

    def __str__(self):
        return self.color_name

class ProductEntry(models.Model):
    productId = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    colorId = models.ForeignKey(ProductColors, on_delete=models.SET_NULL, null=True, blank=True)
    sku = ShortUUIDField(unique = True, length=10, max_length=20, prefix="pro", alphabet="abcdefghijk123456789")
    quantity = models.IntegerField(null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    sale_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

    class Meta:
        verbose_name_plural = "Product Entries"

    def __str__(self):
        return self.sku

class CartItem(models.Model):
    cart_item_id = ShortUUIDField(unique = True, length=10, max_length=20, prefix="cart-item", alphabet="abcdefghijk123456789")
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    sku = models.ForeignKey(ProductEntry, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(null=True,blank=True) 

    class Meta:
        verbose_name_plural = "Cart Items"

    def __str__(self):
        return self.cart_item_id

    
class WishlistItem(models.Model):
    wishlisit_item_id = ShortUUIDField(unique = True, length=10, max_length=27, prefix="wishlist-item", alphabet="abcdefghijk123456789")
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    sku = models.ForeignKey(ProductEntry, on_delete=models.SET_NULL, null=True)

    class Meta:
        verbose_name_plural = "Wishlist Items"

    def __str__(self):
        return self.wishlisit_item_id

main_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView
from .forms import UserSignUpForm, UserSignInForm
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User
from .models import Category, Product, ProductColors, ProductEntry, CartItem, WishlistItem
from .forms import ProductFilterForm
from django.contrib.auth.mixins import LoginRequiredMixin


def Home(request):
    featured_products = Product.objects.filter(featured=True)
    featured_products_with_prices = []

    for product in featured_products:
        product_entry = ProductEntry.objects.filter(productId=product).first()

        product.price = product_entry.price
        product.sku = product_entry.sku
        product.sale_price = product_entry.sale_price

        featured_products_with_prices.append({
        'product': product,
            })
    return render(request, 'home.html', {'products': featured_products_with_prices})

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserSignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
        else:
            error_message = "Invalid sign up - try again"

    form = UserSignUpForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'signup.html', context)

class signin(LoginView):
    form_class = UserSignInForm
    template_name = 'signin.html'

def view_cart(request):
    cart_items = CartItem.objects.filter(user=request.user)
    product_of_the_cart = []
    total_price = 0  

    for cart_item in cart_items:
        try:
            product_entry = ProductEntry.objects.get(sku=cart_item.sku)
            product_info = Product.objects.get(productId=product_entry.productId.productId)
        except ProductEntry.DoesNotExist:
            product_entry = None
        except Product.DoesNotExist:
            product_info = None

        if product_entry and product_info:
            if product_entry.sale_price is not None:
                item_total = product_entry.sale_price * cart_item.quantity  
                total_price += item_total  
            else:
                item_total = product_entry.price * cart_item.quantity  
                total_price += item_total  

            items = {
                'product_info': product_info,
                'product_prices': product_entry,
                'quantity': cart_item.quantity,
                'item_total': item_total,
                'id_of_the_item': cart_item.cart_item_id
            }

            product_of_the_cart.append({
                'items': items
            })

    total_items = len(product_of_the_cart)

    return render(request, "cart/cart.html", {'cart_items': product_of_the_cart, 'total_items': total_items, 'total_price': total_price})


def add_to_cart(request):
    if request.method == "POST":
        sku = request.POST.get('sku')
        if sku:
            try:
                product_entry = ProductEntry.objects.get(sku=sku)
                CartItem.objects.get_or_create(user=request.user, sku=product_entry, quantity=1)
                
            except ProductEntry.DoesNotExist:
                pass
            except Exception as e:
                print(f"Error adding to cart: {e}")
    return redirect('home')

def update_cart(request, cartItemId):
    cart_item = CartItem.objects.get(cart_item_id=cartItemId)
    new_quantity = request.POST.get('quantity')

    if new_quantity and new_quantity.isdigit():
        new_quantity = int(new_quantity)
        if new_quantity > 0:
            cart_item.quantity = new_quantity
            cart_item.save()
        
        else:
            cart_item.delete()
    
    cart_items = CartItem.objects.filter(user=request.user)
    product_of_the_cart = []
    total_price = 0 

    for cart_item in cart_items:
        try:
            product_entry = ProductEntry.objects.get(sku=cart_item.sku)
            product_info = Product.objects.get(productId=product_entry.productId.productId)
        except ProductEntry.DoesNotExist:
            product_entry = None
        except Product.DoesNotExist:
            product_info = None

        if product_entry and product_info:
            if product_entry.sale_price is not None:
                item_total = product_entry.sale_price * cart_item.quantity  
                total_price += item_total  
            else:
                item_total = product_entry.price * cart_item.quantity  
                total_price += item_total   

            items = {
                'product_info': product_info,
                'product_prices': product_entry,
                'quantity': cart_item.quantity,
                'item_total': item_total,
                'id_of_the_item': cart_item.cart_item_id,
                'sku': cart_item.sku
            }

            product_of_the_cart.append({
                'items': items
            })

    total_items = len(product_of_the_cart)

    return render(request, "cart/cart.html", {'cart_items': product_of_the_cart, 'total_items': total_items, 'total_price': total_price})


def show_product(request, sku):
    product_to_find = ProductEntry.objects.get(sku = sku)

    product = {
        'price': product_to_find.price,
        'sale_price': product_to_find.sale_price,
        'sku': product_to_find.sku
    }

    product_info = Product.objects.get(productId = product_to_find.productId.productId)

    product.update({
        'title': product_info.title,
        'product_type': product_info.product_type,
        'image': product_info.image,
        'description': product_info.description,
        'category': product_info.category,
        'brand': product_info.brand
    })

    return render(request, 'products/product-show.html', {'product': product})

def product_search(request):
    form = ProductFilterForm(request.GET or None)
    products = Product.objects.all()

    title = None
    categories = None
    price_min = None
    price_max = None
    brands = None
    

    if form.is_valid():
        title = form.cleaned_data.get('title')
        categories = form.cleaned_data.get('category')
        price_min = form.cleaned_data.get('price_min')
        price_max = form.cleaned_data.get('price_max')
        brands = form.cleaned_data.get('brands')
        

    if title is not None:
        products = products.filter(title__icontains=title)
    if categories:
        products = products.filter(category__in=categories)
    if brands:
        products = products.filter(brand__in=brands)
    if price_min is not None:
        products = products.filter(productentry__price__gte=price_min)
    if price_max is not None:
        products = products.filter(productentry__price__lte=price_max)

    if request.headers.get('HX-Request'):
        return render(request, 'products/product_list.html', {'products': products})

    context = {
        'form': form,
        'products': products
    }

    return render(request, 'products/index.html', {'form': form,
        'products': products})


def add_to_wishlist(request):
    if request.method == "POST":
        sku = request.POST.get('sku')
        if sku:
            try:
                product_entry = ProductEntry.objects.get(sku=sku)
                wishlist_item = WishlistItem.objects.get_or_create(user=request.user, sku=product_entry)
                
            except ProductEntry.DoesNotExist:
                pass
            except Exception as e:
                print(f"Error adding to wishlist: {e}")
    return redirect('home')


def view_wishlist(request):
    wishlist_items = WishlistItem.objects.filter(user=request.user)
    products_of_the_wishlist = []

    for wishlist_item in wishlist_items:
        try:
            product_entry = ProductEntry.objects.get(sku=wishlist_item.sku)
            product_info = Product.objects.get(productId=product_entry.productId.productId)

            items = {
                'product_info': product_info,
                'product_prices': product_entry,
                'id_of_the_item': wishlist_item.wishlisit_item_id,
                'sku': wishlist_item.sku
            }

            products_of_the_wishlist.append({
                'items': items
            })

        except ProductEntry.DoesNotExist:
            product_entry = None
        except Product.DoesNotExist:
            product_info = None

    total_items = len(products_of_the_wishlist)

    return render(request, "wishlist/wishlist.html", {'wishlist_items': products_of_the_wishlist, 'total_items': total_items})

def remove_wishlist_item(request):
    if request.method == "POST":
        sku = request.POST.get('sku')
        if sku:
            try: 
                product_entry = ProductEntry.objects.get(sku=sku)
                wishlist_item = WishlistItem.objects.get(user = request.user, sku = product_entry)
                wishlist_item.delete()
            except Exception as e:
                print(f"Error removing from wishlist: {e}")
    
    return redirect('view_wishlist')

main_app/templates/products/index.html
{% extends 'home.html' %}
{% load static %}

{% block content %}
<section class="section">
    <div class="container">
        <form hx-get="{% url 'product_search' %}" hx-trigger="submit" hx-target="#product-list" hx-swap="innerHTML">
          <label class="label" for="{{ form.title.id_for_label }}">{{ form.title.label }}</label>
            {{form.title}}
            <div class="accordion" id="accordionPanelsStayOpenExample">
              <div class="accordion-item">
                <h2 class="accordion-header" id="panelsStayOpen-headingOne">
                  <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne">
                    <label class="label" for="{{ form.category.id_for_label }}">{{ form.category.label }}</label>
                  </button>
                </h2>
                <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingOne">
                  <div class="accordion-body">
                    {{ form.category }}
                  </div>
                </div>
              </div>
              <div class="accordion-item">
                <h2 class="accordion-header" id="panelsStayOpen-headingTwo">
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
                    <label class="label" for="{{ form.brands.id_for_label }}">{{ form.brands.label }}</label>
                  </button>
                </h2>
                <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingTwo">
                  <div class="accordion-body">
                    {{form.brands}}
                  </div>
                </div>
              </div>
            </div>
            <label class="label" for="{{ form.price_min.id_for_label }}">{{ form.price_min.label }}</label>
            {{ form.price_min }}
            <label class="label" for="{{ form.price_max.id_for_label }}">{{ form.price_max.label }}</label>
            {{ form.price_max }}
            <div class="text-center">
              <button type="submit" class="button is-medium my-3">Search</button>
            </div>
        </form>
        
        <!-- Container where the product list will be updated -->
        <div id="product-list">
            {% include 'products/product_list.html' with products=products %}
        </div>
    </div>
</section>
{% endblock content %}

main_app/templates/products/product-show.html
{% extends 'home.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/products/product-show.css' %}" />
{% endblock head %}

{% block content %}
<div class="row py-5 g-5">
    <div class="col-12 col-lg-6 text-center">
        <img src="{{ product.image }}" 
             alt="" 
             class="m-1" 
             style="object-fit: cover;" 
             data-bs-toggle="modal" 
             data-bs-target="#imageModal"
             >
    </div>
    
    <!-- Modal -->
    <div class="modal fade" id="imageModal" tabindex="-1" aria-labelledby="imageModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-body">
            <img src="{{ product.image }}" 
                 alt="" 
                 class="">
          </div>
        </div>
      </div>
    </div>
    <div class="col-12 col-lg-6 text-center">
        <h2>Product Name: {{ product.title }}</h2>
        <p>Product type: <span>{{ product.product_type }}</span></p>
        <p>category: <span>{{ product.category }}</span></p>
        <p>Brand: {{ product.brand }}</p>
        {% if product.sale_price %}
        <p>Price: {{ product.sale_price }}BD was {{ product.price }}BD </p>
        {% else %}
        <p>Price: {{ product.price }}</p>
        {% endif %}
        <p>Description: {{ product.description }}</p>
        <a  hx-post="{% url 'addtocart' %}" hx-vals='{"sku": "{{ product.sku }}"}' hx-swap="none">
            <span class="icon">
                <i class="fas fa-shopping-bag"></i>
            </span>
        </a>
        <a  hx-post="{% url 'addtowishlist' %}" hx-vals='{"sku": "{{ product.sku }}"}' hx-swap="none">
            <span class="icon">
                <i class="fas fa-heart"></i>
            </span>
        </a>
    </div>

</div>
{% endblock content %}

main_app/templates/products/product_list.html
<div class="columns is-multiline">
    {% for product in products %}
    <div class="column is-one-third">
        <div class="card has-background-link">
            <a href="{% url 'show_product' product.productentry_set.first.sku %}">
                <div class="card">
                    <div class="card-image">
                        <figure class="image is-16by9">
                            <img src="{{ product.image }}" alt="{{ product.title }}" />
                        </figure>
                    </div>
                    <div class="card-content">
                        <div class="media">
                            <div class="media-content">
                                <p class="title is-4">{{ product.title }}</p>
                                <p class=" is-6">price:{{ product.productentry_set.first.price }} BD</p>
                                {% if product.productentry_set.first.sale_price %}
                                <p class=" is-6">sale price:{{ product.productentry_set.first.sale_price }} BD</p>
                                {% endif %}
                                <p class=" is-12">Product Type: {{ product.product_type }}</p>
                                <p class=" is-12">Brand: {{ product.brand }}</p>
                            </div>
                        </div>
                        <div class="content">
                            <a hx-post="{% url 'addtocart' %}" hx-vals='{"sku": "{{ product.productentry_set.first.sku }}"}' hx-swap="none">
                                <span class="icon">
                                    <i class="fas fa-shopping-bag"></i>
                                </span>
                            </a>
                            <a hx-post="{% url 'addtowishlist' %}" hx-vals='{"sku": "{{ product.productentry_set.first.sku }}"}' hx-swap="none">
                                <span class="icon">
                                    <i class="fas fa-heart"></i>
                                </span>
                            </a>
                        </div>
                    </div>
                </div>
            </a>
        </div>
    </div>
    {% empty %}
    <p>No products found.</p>
    {% endfor %}
</div>